project:
  type: website

website:
  navbar:
    logo: "images/logo.png"
    tools:
      - icon: github
        menu:
            - text: Source Code
              url:  https://github.com/PSIAIMS/CAMIS/
            - text: Report a Difference
              url:  https://github.com/PSIAIMS/CAMIS/issues/
    left:
      #- href: index.qmd
      #  text: Home
      - href: about.qmd
        text: "About"
        
      - href: contribution/contribution.qmd
        text: "Contribute"

      - text: "Updates"
        menu: 
          - text: "Meeting minutes"
            href: minutes/index.qmd
          - text: "Conferences 2024"
            href: Conferences.qmd
 
      - text: "Publications"
        href: "https://phuse.s3.eu-central-1.amazonaws.com/Deliverables/Data+Visualisation+%26+Open+Source+Technology/WP077.pdf"
      

format:
  html:
    toc: true
    theme:
      light: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css


editor: visual

